XVimProject/XVim2

- README.md
- SIGNING_Xcode.md
The installation instructions were a little confusing to me, so I took a crack at improving them. Namely, this PR:
- Renames INSTALL_Xcode.md to SIGNING_Xcode.md and removes references to it as a set of installation instructions, because it is not a complete set of installation instructions.
- Promotes the re-codesigning of Xcode to a first-class citizen in the installation instructions.
This PR does not include a similar update to the README_jp.md because I do not know Japanese. Perhaps we can open an issue to get that updated as well.
> Clarified installation instructions

- README_jp.md
I found a dead link at the head of the `README.md` for this project and fixed it.
Also, I updated to follow `README.md` of XVim2's latest master branch.
> Restore a link to japanese translation

- XVim2/SourceViewProtocol.h
- XVim2/XVim/XVimDefs.h
- XVim2/XVim/XVimNormalEvaluator.m
- XVim2/XVim/XVimVisualEvaluator.m
- XVim2/Xcode/SourceCodeEditorViewProxy+Scrolling.m
Hi XVim developers.
Scroll one line motions(`C_e` and `C_y`) implementation are  already almost finished and marked as TODO.
I change `-[xvim_scroll:count:]` method to support line scroll and call it from `C_e` and `C_y`.
Thanks.
> Add support C-e and C-y scroll line motions.

- XVim2/Xcode/SourceCodeEditorViewProxy+Scrolling.m
don't move cursor on ctrl-e, ctrl-y except to keep it on the screen.  This is how vim works.
> don't move cursor on ctrl-e, ctrl-y

- XVim2/Xcode/Swift/SourceCodeEditorViewWrapper.swift
This fixes the selection on Xcode 10 beta 3, on which the signature of `addSelectedRange:modifiers:` was changed to `addSelectedRange:modifiers:scrollPlacement:alwaysScroll:`.
```
unmangled:
SourceEditor.SourceEditorView.addSelectedRange(_: SourceEditor.SourceEditorRange, modifiers: SourceEditor.SourceEditorSelectionModifiers, scrollPlacement: SourceEditor.ScrollPlacement?, alwaysScroll: Swift.Bool) -> ()
mangled:
_$S12SourceEditor0aB4ViewC16addSelectedRange_9modifiers15scrollPlacement12alwaysScrollyAA0abF0V_AA0aB18SelectionModifiersVAA0kI0OSgSbtF
```
If we want to keep in sync the definition of the methods on the wrapper objects we might need to change as well on SourceCodeEditorViewWrapper.swift.
> xcode10 b3 - fix selection on source editor

- README.md
It seems there has never been a CONTRIBUTING.md file so the link to it
in the README is dead. For now, this removes the link but in future we
should update the project with some contributing instructions
> Remove contributing guidelines from the README

- README.md
- why_resign_xcode.md
I thought it might be useful to add some documentation to explain the reasons why users must resign their versions of Xcode in order to use XVim2. Hopefully this will help to increase people's confidence in using the tool and reduce any unnecessary issues being created 👍.
> Add an FAQ on why users need to resign Xcode to use Xvim2

- XVim2/XVim/XVim.h
- XVim2/XVim/XVim.m
- XVim2/XVim/XVimExCommand.m
Fix for #176 to allow reloading of the xvimrc.  Also implements `source:inWindow` so that the `source` command can be used.
> Fix for #176 to allow sourcing xvimrc

- XVim2/Xcode/XVimIDEPegasusSourceEditorView.m
The IDEConsoleEditorView didn't need commandline, actually it
didn't need XVim, Fix #170
> Only enable XVim for IDESourceEditorView

- XVim2/UnitTest/XVimTester+Register.m
- XVim2/XVim/Evaluator/XVimEvaluator.m
- XVim2/XVim/SourceViewProtocol.h
- XVim2/XVim/XVimRegister.h
- XVim2/XVim/XVimRegister.m
- XVim2/Xcode/SourceCodeEditorViewProxy+Operations.m
In order to resolve #214 
> ### Operation
> If I yank to register a, then yank to register b, then put register a to replace string C, then register a will have C and b will remain unchanged.
> 
> ### Expected behaviour
> When putting a register's contents, whatever gets replaced should go into the default register but not the specific register used. At least that's the default behavior in my version of Vim.
> Fix for put from register in visual mode

- XVim2/Info.plist
I added the UUID for Xcode 11.2 in `Info.plist` file.
> Add UUID for Xcode 11.2

- XVim2/Xcode/SourceEditorViewProxy.m
- XVim2/XcodeHeader/SourceEditor/SourceEditorScrollView.h
This readds support for showing the command input bar in a way that is compatible with Xcode12.
I have verified that this also works on Xcode11.7.
Closes #310
> Fixes command line input bar for Xcode12

- XVim2/XVim/XVim.m
- XVim2/XcodeHeader/DVTKit/DVTFoldingLayoutManagerDelegate-Protocol.h
- XVim2/XcodeHeader/DVTKit/DVTTextCompletionSupportingTextView-Protocol.h
- XVim2/XcodeHeader/DVTKit/NSControlTextEditingDelegate-Protocol.h
- XVim2/XcodeHeader/DVTKit/NSTableViewDelegate-Protocol.h
- XVim2/XcodeHeader/IDEKit/DVTCompletingTextViewDelegate-Protocol.h
- XVim2/XcodeHeader/IDEKit/DVTSplitViewDelegate-Protocol.h
- XVim2/XcodeHeader/IDEKit/IDEConsoleArea.h
- XVim2/XcodeHeader/IDESourceEditor/_TtC15IDESourceEditor20IDEConsoleEditorView.h
Enables support for printing registers using `:reg`
Closes #123
> Print registers using :reg

- XVim2/Info.plist
This pull request adds the UUID of Xcode 12.2 (12B45b).
> Add Xcode 12.2 UUID

- XVim2/Xcode/SourceEditorViewProxy+Scrolling.m
- XVim2/Xcode/SourceEditorViewProxy.h
- XVim2/Xcode/SourceEditorViewProxy.m
hi @pebble8888 
fixed #315 
This PR fixed line based position calculated scroll features.
Only tested on Xcode 12.2
> fix: Ctrl+E and Ctrl+Y feature and line based scroll feature

- XVim2/Xcode/SourceEditorViewProxy+Scrolling.m
- XVim2/Xcode/SourceEditorViewProxy+XVim.h
- XVim2/Xcode/SourceEditorViewProxy+XVim.m
Hi @pebble8888 
`H`, `M` and `L` motion still getting wrong line number in Xcode 12 after fixing for `+Scrolling` impl by #345.
This PR use `xvim_visibleLineRange` method to getting correct visible line range also for `+XVim` impl to fixing `H`, `M`, and `L` motion.
> Fix H, M and L motion

- .github/workflows/main.yml
github actions provided mac are only supported intel yet.
----
Currently, this CI will check compile able status.
I want to run unit test that implemented inside XVim menu but it is difficult in CI.
- Could not create unit test target for bundle target (XVim2.xcplugin) to invoke by `xcodebuild test`
- Required create self cert then replace codesign of Xcode in CI. It's maybe too long.
- Could not get unit test result for now, only display window.
> Add CI by GitHub Actions

- XVim2/Xcode/SourceEditorViewWrapper.s
While researching assembly code porting to arm64, I found `rbx`, `r12-r15` and `xmm0-7` register is not used around invoking swift method.
Additionally, rest of using registers `rsi, rdi, rdx, rcx, r8 and r9` are not callee-save registers.
This PR remove operations using that registers and refactoring before support arm.
> Refactor assembly code

- Makefile
- README.md
- XVim2/Info.plist
- XVim2/XVim/XVim.m
Add support SIMBL (MacForge) library loading system to workaround sign-in to Apple ID via Xcode issue.
https://github.com/MacEnhance/MacForge
This change is no side effect to current Xcode plugin loading system.
ref: #340 #323
> Add support SIMBL library loading system

- XVim2/Xcode/SourceEditorViewProxy+Operations.m
Fix #144
Fix #363
Fix #271
do you have any concern move cursor (selectedRange) before enter to insert mode?
> Add workaround for current cursor position character temporary invisible when Shift+o
